name: Publish to npm

on:
  push:
    branches:
      - main # Only publish when code is pushed to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Specify your Node.js version
          registry-url: 'https://registry.npmjs.org'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish